[profile.default]
bytecode_hash = "none"
evm_version = "cancun"
ffi = true
fs_permissions = [{access = "read-write", path = ".forge-snapshots/"}]
libs = ["lib"]
out = "out"
solc_version = "0.8.30"
src = "src"
via_ir = false
optimizer_runs = 44444444

[fuzz]
runs = 3000

[rpc_endpoints]
unichain_sepolia = "${UNICHAIN_SEPOLIA_RPC_URL}"

[lint]
exclude_lints = ["screaming-snake-case-immutable", "screaming-snake-case-const"]
lint_on_build = false
